// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHmOynRYYc0tgaG6UNDSssc2DLKS1OjQY',
    appId: '1:2091922007:web:566991214602b4f1d36912',
    messagingSenderId: '2091922007',
    projectId: 'bmi-calculater-e6db6',
    authDomain: 'bmi-calculater-e6db6.firebaseapp.com',
    storageBucket: 'bmi-calculater-e6db6.appspot.com',
    measurementId: 'G-LKD6KWM3JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkzBYKqntIKBpYTTxG202FfsbgR7IzJSM',
    appId: '1:2091922007:android:ccd4e63b1eab4c08d36912',
    messagingSenderId: '2091922007',
    projectId: 'bmi-calculater-e6db6',
    storageBucket: 'bmi-calculater-e6db6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_qFy5Exgdm4UulGYpq3W1ypLW-bszD-k',
    appId: '1:2091922007:ios:4c0c0f92a9f65794d36912',
    messagingSenderId: '2091922007',
    projectId: 'bmi-calculater-e6db6',
    storageBucket: 'bmi-calculater-e6db6.appspot.com',
    iosBundleId: 'com.example.bmiCalulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_qFy5Exgdm4UulGYpq3W1ypLW-bszD-k',
    appId: '1:2091922007:ios:4c0c0f92a9f65794d36912',
    messagingSenderId: '2091922007',
    projectId: 'bmi-calculater-e6db6',
    storageBucket: 'bmi-calculater-e6db6.appspot.com',
    iosBundleId: 'com.example.bmiCalulator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHmOynRYYc0tgaG6UNDSssc2DLKS1OjQY',
    appId: '1:2091922007:web:c21c284a7193f2afd36912',
    messagingSenderId: '2091922007',
    projectId: 'bmi-calculater-e6db6',
    authDomain: 'bmi-calculater-e6db6.firebaseapp.com',
    storageBucket: 'bmi-calculater-e6db6.appspot.com',
    measurementId: 'G-RF0NLS1N7P',
  );
}
